### ISSUE TITLE
Typo in OnSearchDeviceListener interface

### ISSUE THREAD

**Issue by pwittchen** [a-voyager/BluetoothHelper#1]
In line:
https://github.com/a-voyager/BluetoothHelper/blob/b3b439cf9b4b6596c105aa026ab7890dcc42e0e3/bthelper/src/main/java/top/wuhaojie/bthelper/OnSearchDeviceListener.java#L22

we have

``` java
void onNewDeviceFounded(BluetoothDevice device);
```

but it should be

``` java
void onNewDeviceFound(BluetoothDevice device);
```

**Comment by a-voyager** [comment]
Sorry for my bad English. I have updated it.

**Comment by pwittchen** [comment]
Your English is fine. This was just a small typo and everyone could do that. :)

Thanks!
