### ISSUE TITLE
为啥不能在android studio中引用库

### ISSUE THREAD

**Issue by wangse** [a-voyager/BluetoothHelper#4]
出现错误：
Failed to resolve: com.github.a-voyager:BluetoothHelper:f71d40a98b
Show in File
Show in Project Structure dialog

**Comment by wangse** [comment]
已经下载本地编译成aar文件导入android studio了，aar文件目录为：bthelper/build/outputs/aar/

**Comment by a-voyager** [comment]
是不是忘记修改根目录的gradle了？或者网络不通？

**Comment by a-voyager** [comment]
是不是忘记修改根目录的gradle了？或者网络不通？

**Comment by wangse** [comment]
修改了，加了这个 maven { url "https://jitpack.io" }，网络是通的，加其他的库都可以加
